// Serverless In-Memory Cloud Sync State for URSPantropiko Ticket Suite
const SAMPLE_TEST_ATTENDEES = [
  // --- COLLEGE OF BUSINESS (15 Students) ---
  { id: 'CB-01', ticket_code: 'TKT-20001', student_id: '2024-01001', full_name: 'Abad, Christian Paul', department: 'College of Business', year_level: '1st Year', program_section: 'BSBA 1-A', payment_status: 'paid', day1_status: 'attended', day1_time: '08:14 AM', day2_status: 'not_attended', day2_time: null, attendance_status: 'attended' },
  { id: 'CB-02', ticket_code: 'TKT-20002', student_id: '2024-01002', full_name: 'Alcantara, Bianca Mae', department: 'College of Business', year_level: '1st Year', program_section: 'BSBA 1-B', payment_status: 'unpaid', day1_status: 'not_attended', day1_time: null, day2_status: 'not_attended', day2_time: null, attendance_status: 'not_attended' },
  { id: 'CB-03', ticket_code: 'TKT-20003', student_id: '2023-01003', full_name: 'Aquino, Gerald Kim', department: 'College of Business', year_level: '2nd Year', program_section: 'BSA 2-A', payment_status: 'paid', day1_status: 'attended', day1_time: '08:26 AM', day2_status: 'attended', day2_time: '08:15 PM', attendance_status: 'attended' },
  { id: 'CB-04', ticket_code: 'TKT-20004', student_id: '2023-01004', full_name: 'Bautista, Janelle Rose', department: 'College of Business', year_level: '2nd Year', program_section: 'BSA 2-B', payment_status: 'unpaid', day1_status: 'not_attended', day1_time: null, day2_status: 'not_attended', day2_time: null, attendance_status: 'not_attended' },
  { id: 'CB-05', ticket_code: 'TKT-20005', student_id: '2022-01005', full_name: 'Castillo, Mark Anthony', department: 'College of Business', year_level: '3rd Year', program_section: 'BSBA 3-A', payment_status: 'paid', day1_status: 'not_attended', day1_time: null, day2_status: 'not_attended', day2_time: null, attendance_status: 'not_attended' },
  { id: 'CB-06', ticket_code: 'TKT-20006', student_id: '2022-01006', full_name: 'De Guzman, Patricia', department: 'College of Business', year_level: '3rd Year', program_section: 'BSBA 3-B', payment_status: 'unpaid', day1_status: 'not_attended', day1_time: null, day2_status: 'not_attended', day2_time: null, attendance_status: 'not_attended' },
  { id: 'CB-07', ticket_code: 'TKT-20007', student_id: '2021-01007', full_name: 'Domingo, Ralph Vincent', department: 'College of Business', year_level: '4th Year', program_section: 'BSA 4-A', payment_status: 'paid', day1_status: 'attended', day1_time: '08:35 AM', day2_status: 'not_attended', day2_time: null, attendance_status: 'attended' },
  { id: 'CB-08', ticket_code: 'TKT-20008', student_id: '2021-01008', full_name: 'Esguerra, Stephanie Jane', department: 'College of Business', year_level: '4th Year', program_section: 'BSA 4-B', payment_status: 'paid', day1_status: 'attended', day1_time: '08:40 AM', day2_status: 'attended', day2_time: '08:30 PM', attendance_status: 'attended' },
  { id: 'CB-09', ticket_code: 'TKT-20009', student_id: '2024-01009', full_name: 'Flores, Joshua Luke', department: 'College of Business', year_level: '1st Year', program_section: 'BSBA 1-A', payment_status: 'unpaid', day1_status: 'not_attended', day1_time: null, day2_status: 'not_attended', day2_time: null, attendance_status: 'not_attended' },
  { id: 'CB-10', ticket_code: 'TKT-20010', student_id: '2023-01010', full_name: 'Garcia, Katrina Danielle', department: 'College of Business', year_level: '2nd Year', program_section: 'BSA 2-A', payment_status: 'paid', day1_status: 'attended', day1_time: '08:22 AM', day2_status: 'not_attended', day2_time: null, attendance_status: 'attended' },
  { id: 'CB-11', ticket_code: 'TKT-20011', student_id: '2022-01011', full_name: 'Hernandez, Justin Clyde', department: 'College of Business', year_level: '3rd Year', program_section: 'BSBA 3-A', payment_status: 'paid', day1_status: 'attended', day1_time: '08:15 AM', day2_status: 'not_attended', day2_time: null, attendance_status: 'attended' },
  { id: 'CB-12', ticket_code: 'TKT-20012', student_id: '2021-01012', full_name: 'Ignacio, Camille Marie', department: 'College of Business', year_level: '4th Year', program_section: 'BSA 4-A', payment_status: 'unpaid', day1_status: 'not_attended', day1_time: null, day2_status: 'not_attended', day2_time: null, attendance_status: 'not_attended' },
  { id: 'CB-13', ticket_code: 'TKT-20013', student_id: '2024-01013', full_name: 'Lim, Chloe Denise', department: 'College of Business', year_level: '1st Year', program_section: 'BSBA 1-B', payment_status: 'paid', day1_status: 'attended', day1_time: '08:22 AM', day2_status: 'attended', day2_time: '08:30 PM', attendance_status: 'attended' },
  { id: 'CB-14', ticket_code: 'TKT-20014', student_id: '2023-01014', full_name: 'Mendoza, Danilo Jr.', department: 'College of Business', year_level: '2nd Year', program_section: 'BSA 2-B', payment_status: 'paid', day1_status: 'attended', day1_time: '08:40 AM', day2_status: 'not_attended', day2_time: null, attendance_status: 'attended' },
  { id: 'CB-15', ticket_code: 'TKT-20015', student_id: '2021-01015', full_name: 'Tan, Sophia Nicole', department: 'College of Business', year_level: '4th Year', program_section: 'BSBA 4-B', payment_status: 'unpaid', day1_status: 'not_attended', day1_time: null, day2_status: 'not_attended', day2_time: null, attendance_status: 'not_attended' },

  // --- COLLEGE OF EDUCATION (15 Students) ---
  { id: 'COED-01', ticket_code: 'TKT-30001', student_id: '2024-02001', full_name: 'Alano, Kimberly Joyce', department: 'College of Education', year_level: '1st Year', program_section: 'BSED 1-A', payment_status: 'paid', day1_status: 'attended', day1_time: '08:10 AM', day2_status: 'not_attended', day2_time: null, attendance_status: 'attended' },
  { id: 'COED-02', ticket_code: 'TKT-30002', student_id: '2024-02002', full_name: 'Bernardo, Kevin James', department: 'College of Education', year_level: '1st Year', program_section: 'BEED 1-B', payment_status: 'unpaid', day1_status: 'not_attended', day1_time: null, day2_status: 'not_attended', day2_time: null, attendance_status: 'not_attended' },
  { id: 'COED-03', ticket_code: 'TKT-30003', student_id: '2023-02003', full_name: 'Cabrera, Mary Grace', department: 'College of Education', year_level: '2nd Year', program_section: 'BTLED 2-A', payment_status: 'paid', day1_status: 'attended', day1_time: '08:30 AM', day2_status: 'attended', day2_time: '08:20 PM', attendance_status: 'attended' },
  { id: 'COED-04', ticket_code: 'TKT-30004', student_id: '2023-02004', full_name: 'Cruz, John Michael', department: 'College of Education', year_level: '2nd Year', program_section: 'BSED 2-B', payment_status: 'paid', day1_status: 'not_attended', day1_time: null, day2_status: 'not_attended', day2_time: null, attendance_status: 'not_attended' },
  { id: 'COED-05', ticket_code: 'TKT-30005', student_id: '2022-02005', full_name: 'Diaz, Angela Mae', department: 'College of Education', year_level: '3rd Year', program_section: 'BEED 3-B', payment_status: 'unpaid', day1_status: 'not_attended', day1_time: null, day2_status: 'not_attended', day2_time: null, attendance_status: 'not_attended' },
  { id: 'COED-06', ticket_code: 'TKT-30006', student_id: '2022-02006', full_name: 'Enriquez, Lance Matthew', department: 'College of Education', year_level: '3rd Year', program_section: 'BSED 3-A', payment_status: 'paid', day1_status: 'attended', day1_time: '08:18 AM', day2_status: 'not_attended', day2_time: null, attendance_status: 'attended' },
  { id: 'COED-07', ticket_code: 'TKT-30007', student_id: '2021-02007', full_name: 'Francisco, Andrea Nicole', department: 'College of Education', year_level: '4th Year', program_section: 'BTLED 4-A', payment_status: 'paid', day1_status: 'attended', day1_time: '08:45 AM', day2_status: 'attended', day2_time: '08:40 PM', attendance_status: 'attended' },
  { id: 'COED-08', ticket_code: 'TKT-30008', student_id: '2021-02008', full_name: 'Gomez, Patricia Anne', department: 'College of Education', year_level: '4th Year', program_section: 'BSED 4-B', payment_status: 'paid', day1_status: 'attended', day1_time: '08:35 AM', day2_status: 'not_attended', day2_time: null, attendance_status: 'attended' },
  { id: 'COED-09', ticket_code: 'TKT-30009', student_id: '2024-02009', full_name: 'Hilario, Daniel Joseph', department: 'College of Education', year_level: '1st Year', program_section: 'BEED 1-A', payment_status: 'unpaid', day1_status: 'not_attended', day1_time: null, day2_status: 'not_attended', day2_time: null, attendance_status: 'not_attended' },
  { id: 'COED-10', ticket_code: 'TKT-30010', student_id: '2023-02010', full_name: 'Javier, Roxanne Claire', department: 'College of Education', year_level: '2nd Year', program_section: 'BTLED 2-A', payment_status: 'paid', day1_status: 'attended', day1_time: '08:25 AM', day2_status: 'not_attended', day2_time: null, attendance_status: 'attended' },
  { id: 'COED-11', ticket_code: 'TKT-30011', student_id: '2022-02011', full_name: 'Laureano, Gabriel Ethan', department: 'College of Education', year_level: '3rd Year', program_section: 'BSED 3-A', payment_status: 'unpaid', day1_status: 'not_attended', day1_time: null, day2_status: 'not_attended', day2_time: null, attendance_status: 'not_attended' },
  { id: 'COED-12', ticket_code: 'TKT-30012', student_id: '2021-02012', full_name: 'Magno, Bea Marie', department: 'College of Education', year_level: '4th Year', program_section: 'BTLED 4-A', payment_status: 'paid', day1_status: 'attended', day1_time: '08:50 AM', day2_status: 'not_attended', day2_time: null, attendance_status: 'attended' },
  { id: 'COED-13', ticket_code: 'TKT-30013', student_id: '2024-02013', full_name: 'Navarro, Clarisse Joy', department: 'College of Education', year_level: '1st Year', program_section: 'BEED 1-B', payment_status: 'paid', day1_status: 'not_attended', day1_time: null, day2_status: 'not_attended', day2_time: null, attendance_status: 'not_attended' },
  { id: 'COED-14', ticket_code: 'TKT-30014', student_id: '2023-02014', full_name: 'Ocampo, Patrick Neil', department: 'College of Education', year_level: '2nd Year', program_section: 'BSED 2-A', payment_status: 'unpaid', day1_status: 'not_attended', day1_time: null, day2_status: 'not_attended', day2_time: null, attendance_status: 'not_attended' },
  { id: 'COED-15', ticket_code: 'TKT-30015', student_id: '2022-02015', full_name: 'Reyes, John Carlo', department: 'College of Education', year_level: '3rd Year', program_section: 'BSED 3-A', payment_status: 'paid', day1_status: 'attended', day1_time: '08:14 AM', day2_status: 'not_attended', day2_time: null, attendance_status: 'attended' },

  // --- COLLEGE OF SOCIAL SCIENCES (15 Students) ---
  { id: 'CSS-01', ticket_code: 'TKT-40001', student_id: '2024-03001', full_name: 'Agustin, Cedric Liam', department: 'College of Social Sciences', year_level: '1st Year', program_section: 'BS-PSYCH 1-A', payment_status: 'paid', day1_status: 'attended', day1_time: '08:12 AM', day2_status: 'not_attended', day2_time: null, attendance_status: 'attended' },
  { id: 'CSS-02', ticket_code: 'TKT-40002', student_id: '2024-03002', full_name: 'Beltran, Dianne Rose', department: 'College of Social Sciences', year_level: '1st Year', program_section: 'AB-POLSCI 1-B', payment_status: 'unpaid', day1_status: 'not_attended', day1_time: null, day2_status: 'not_attended', day2_time: null, attendance_status: 'not_attended' },
  { id: 'CSS-03', ticket_code: 'TKT-40003', student_id: '2023-03003', full_name: 'Cruz, Mark Kevin', department: 'College of Social Sciences', year_level: '2nd Year', program_section: 'AB-POLSCI 2-A', payment_status: 'paid', day1_status: 'attended', day1_time: '08:26 AM', day2_status: 'attended', day2_time: '08:15 PM', attendance_status: 'attended' },
  { id: 'CSS-04', ticket_code: 'TKT-40004', student_id: '2023-03004', full_name: 'David, Justine Faye', department: 'College of Social Sciences', year_level: '2nd Year', program_section: 'BS-PSYCH 2-B', payment_status: 'paid', day1_status: 'not_attended', day1_time: null, day2_status: 'not_attended', day2_time: null, attendance_status: 'not_attended' },
  { id: 'CSS-05', ticket_code: 'TKT-40005', student_id: '2022-03005', full_name: 'Esteban, Ryan Gabriel', department: 'College of Social Sciences', year_level: '3rd Year', program_section: 'AB-SOC 3-A', payment_status: 'unpaid', day1_status: 'not_attended', day1_time: null, day2_status: 'not_attended', day2_time: null, attendance_status: 'not_attended' },
  { id: 'CSS-06', ticket_code: 'TKT-40006', student_id: '2022-03006', full_name: 'Fernandez, Alyssa Joy', department: 'College of Social Sciences', year_level: '3rd Year', program_section: 'BS-PSYCH 3-A', payment_status: 'paid', day1_status: 'attended', day1_time: '08:20 AM', day2_status: 'not_attended', day2_time: null, attendance_status: 'attended' },
  { id: 'CSS-07', ticket_code: 'TKT-40007', student_id: '2021-03007', full_name: 'Gutierrez, Sean Marcus', department: 'College of Social Sciences', year_level: '4th Year', program_section: 'AB-POLSCI 4-A', payment_status: 'paid', day1_status: 'attended', day1_time: '08:35 AM', day2_status: 'attended', day2_time: '08:45 PM', attendance_status: 'attended' },
  { id: 'CSS-08', ticket_code: 'TKT-40008', student_id: '2021-03008', full_name: 'Herrera, Valerie Anne', department: 'College of Social Sciences', year_level: '4th Year', program_section: 'BS-PSYCH 4-B', payment_status: 'unpaid', day1_status: 'not_attended', day1_time: null, day2_status: 'not_attended', day2_time: null, attendance_status: 'not_attended' },
  { id: 'CSS-09', ticket_code: 'TKT-40009', student_id: '2024-03009', full_name: 'Isidro, Kyle Dominic', department: 'College of Social Sciences', year_level: '1st Year', program_section: 'AB-SOC 1-A', payment_status: 'paid', day1_status: 'attended', day1_time: '08:15 AM', day2_status: 'not_attended', day2_time: null, attendance_status: 'attended' },
  { id: 'CSS-10', ticket_code: 'TKT-40010', student_id: '2023-03010', full_name: 'Jimenez, Sarah Louise', department: 'College of Social Sciences', year_level: '2nd Year', program_section: 'BS-PSYCH 2-A', payment_status: 'paid', day1_status: 'attended', day1_time: '08:30 AM', day2_status: 'not_attended', day2_time: null, attendance_status: 'attended' },
  { id: 'CSS-11', ticket_code: 'TKT-40011', student_id: '2022-03011', full_name: 'Morales, Joshua', department: 'College of Social Sciences', year_level: '3rd Year', program_section: 'BS-PSYCH 3-A', payment_status: 'paid', day1_status: 'not_attended', day1_time: null, day2_status: 'not_attended', day2_time: null, attendance_status: 'not_attended' },
  { id: 'CSS-12', ticket_code: 'TKT-40012', student_id: '2021-03012', full_name: 'Noriega, Francine Gail', department: 'College of Social Sciences', year_level: '4th Year', program_section: 'AB-POLSCI 4-B', payment_status: 'unpaid', day1_status: 'not_attended', day1_time: null, day2_status: 'not_attended', day2_time: null, attendance_status: 'not_attended' },
  { id: 'CSS-13', ticket_code: 'TKT-40013', student_id: '2024-03013', full_name: 'Pascual, Brian Dave', department: 'College of Social Sciences', year_level: '1st Year', program_section: 'BS-PSYCH 1-B', payment_status: 'paid', day1_status: 'attended', day1_time: '08:18 AM', day2_status: 'not_attended', day2_time: null, attendance_status: 'attended' },
  { id: 'CSS-14', ticket_code: 'TKT-40014', student_id: '2023-03014', full_name: 'Quizon, Mikaela Marie', department: 'College of Social Sciences', year_level: '2nd Year', program_section: 'AB-SOC 2-A', payment_status: 'unpaid', day1_status: 'not_attended', day1_time: null, day2_status: 'not_attended', day2_time: null, attendance_status: 'not_attended' },
  { id: 'CSS-15', ticket_code: 'TKT-40015', student_id: '2022-03015', full_name: 'Santos, Gabriel', department: 'College of Social Sciences', year_level: '3rd Year', program_section: 'AB-SOC 3-A', payment_status: 'paid', day1_status: 'attended', day1_time: '08:40 AM', day2_status: 'not_attended', day2_time: null, attendance_status: 'attended' }
];

let cachedAttendees = SAMPLE_TEST_ATTENDEES;

export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method === 'POST' || req.method === 'PUT') {
    try {
      const data = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
      if (Array.isArray(data)) {
        cachedAttendees = data;
      } else if (data && data.tickets && Array.isArray(data.tickets)) {
        cachedAttendees = data.tickets;
      } else if (data && data.attendee) {
        if (!cachedAttendees) cachedAttendees = [];
        cachedAttendees = [data.attendee, ...cachedAttendees.filter(a => a.ticket_code !== data.attendee.ticket_code && a.student_id !== data.attendee.student_id)];
      }
      return res.status(200).json({ success: true, count: (cachedAttendees || []).length, data: cachedAttendees });
    } catch (e) {
      return res.status(400).json({ error: 'Invalid JSON body' });
    }
  }

  // GET: Pure state fetch with NO stale event replay
  return res.status(200).json({ success: true, data: cachedAttendees || SAMPLE_TEST_ATTENDEES });
}
